services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile-dev
    env_file:
      - .env
      - .env.local
    environment:
      NODE_ENV: production
    volumes:
      - ./config:/usr/src/app/config